server {
    listen 80;
    listen 443 ssl;
    server_name g.0xy.fr
			    gita.0xy.fr
				www.gita.0xy.fr
                www.g.0xy.fr;
    
    ssl_certificate     /var/www/magictintin/certs/xyc;
    ssl_certificate_key /var/www/magictintin/certs/xyk;

    root /var/www/magictintin/gita;

	index index.php;# index.html;

	location / {
	    index index.php;
	    try_files $uri $uri/ @php_fallback;
	}

	location @php_fallback {
        rewrite ^(.+)$ $1.php last;
    }

    include /var/www/magictintin/php.conf;
}
